### ISSUE TITLE
file path gets overriden during the upload

### ISSUE THREAD

**Issue by dinisnunes1** [muhamedzeema/appgallery-deply-action#4]
I'm using this action to upload to AppGallery, the apk is uploaded but the filename is always overriden on AppGallery and is always shown as `app-release.apk`

Example of  the used config
```     
 - name: Deploy to Huawei App Gallery
   uses: muhamedzeema/appgallery-deply-action@main
   with:
      client-id: ${{secrets.HUAWEI_CLIENT_ID}}
      client-key: ${{secrets.HUAWEI_CLIENT_KEY}}
      app-id: ${{secrets.HUAWEI_APP_ID}}
      file-extension: "apk"
      file-path: "path/android_test_universal.apk"
      submit: false
```
![Screenshot 2022-01-10 at 15 58 02](https://user-images.githubusercontent.com/12532273/148796886-8218abea-d4e4-4a85-8155-cf49032a3bf4.png)

**Comment by muhamedzeema** [comment]
@dinisnunes1 I will check it tomorrow morning and get back to you

**Comment by dinisnunes1** [comment]
@muhamedzeema I beleive it's this line https://github.com/muhamedzeema/appgallery-deply-action/blob/main/index.js#L130 as the file name is hardcoded.

**Comment by dinisnunes1** [comment]
@muhamedzeema quick fix could be:
**Option 1**

- Add a new Input (can be optional), something like:

```      
- name: Deploy to Huawei App Gallery
  uses: muhamedzeema/appgallery-deply-action@main
  with:
    client-id: ${{secrets.HUAWEI_CLIENT_ID}}
    client-key: ${{secrets.HUAWEI_CLIENT_KEY}}
    app-id: ${{secrets.HUAWEI_APP_ID}}
    file-extension: "apk"
    file-path: "apk/release/app-release.apk"
    file-name: "Example-of-my-app-file-name"
    submit: true
```

and then edit the function updateAppFileInfo
```
function updateAppFileInfo({ fileDestUrl, size, appId, clientId, token, fileName, fileExt }) {
  console.log("Update App File Info .... ⌛️");
  var binaryName = 'app-release'
  if (typeOf(fileName) != 'undefined' && fileName != '') {
      binaryName = fileName
  }
  var data = JSON.stringify({
    fileType: "5",
    files: [
      {
        fileName: `${binaryName}.${fileExt}`,
        fileDestUrl: fileDestUrl,
        size,
      },
    ],
  });
```

**Option 2**

- Extract the file name as a substring between the / chat and the extension file. Example for 
`
file-path: "apk/release/app-release.apk"
`
try to extract between last / char and the .apk text.
